channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  # main
  - attrs
  - pint
  # tests
  - pytest
  - pytest-cov
  # dev
  - black
  - bump2version
  - click
  - conda-lock
  - isort
  - pip
  - pip-tools
  - ruamel.yaml
  - setuptools
  - twine
  # docs
  - sphinx>=3.1
  - furo
  - sphinx-copybutton
  - sphinx-autodoc-typehints
